<%@ Page Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true" CodeFile="frmEmployeeDelation.aspx.cs" Inherits="Admin_AdminUserControl_frmEmployeeDelation" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <table align="center" border ="0" cellpadding="0" cellspacing="0" style="width: 251px">
    <tr>
        <td colspan="2" align="center">
            &nbsp;&nbsp;
        </td>
    </tr>
        <tr>
            <td colspan="2" align="center" ><asp:Label ID="smlcsmc" runat="server" 
                    Text="Employee Deletion" Font-Bold="True" Font-Size="X-Large" 
                    ForeColor="#0033CC" />
                </td>
        </tr>
    <tr>
        <td colspan="2" style="width: 183px; height: 23px; text-align: center">
            &nbsp;&nbsp;
        </td>
    </tr>
        <tr>
            <td colspan="2" style="text-align: center" >
                <asp:DetailsView ID="DetailsEmpView" runat="server" Height="50px" Width="125px" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellPadding="3" OnItemUpdating="DetailsEmpView_ItemUpdating" OnItemDeleting="DetailsEmpView_ItemDeleting" OnPageIndexChanging="DetailsEmpView_PageIndexChanging" DataKeyNames="EmpId" AutoGenerateDeleteButton="True" OnItemCommand="DetailsEmpView_ItemCommand" CellSpacing="2">
               <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
                    <EditRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
                    <RowStyle ForeColor="#8C4510" BackColor="#FFF7E7" />
                    <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
                    <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
                    
                </asp:DetailsView>
                
            </td>
        </tr>
    <tr>
        <td colspan="2" style="text-align: center">
            &nbsp;&nbsp;
        </td>
    </tr>
        <tr>
            <td colspan="2" align="center">
                <asp:Button ID="BtnCancel" runat="server" CssClass="btnstyle" Text="Cancel" OnClick="BtnCancel_Click" />
            </td>
        </tr>
    </table>

</asp:Content>

